# Generated by Django 6.0.6 on 2026-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your publisher name...', max_length=50)),
                ('website', models.URLField(blank=True, help_text='Enter your publisher website...')),
                ('email', models.EmailField(blank=True, help_text='Enter your publisher email...', max_length=254)),
            ],
        ),
    ]
