# Generated by Django 6.0.6 on 2026-06-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herpain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name...', max_length=50)),
                ('last_name', models.CharField(help_text='Enter your last name...', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Enter your email...', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your book title...', max_length=70)),
                ('publication_date', models.DateField(verbose_name='Date of the publication')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN Number of the book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herpain.publisher')),
            ],
        ),
    ]
