# Generated by Django 6.0.6 on 2026-06-12 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herpain', '0002_contributor_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co_Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='The role of the contributor in this book')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herpain.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herpain.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='contributor',
            field=models.ManyToManyField(through='herpain.BookContributor', to='herpain.contributor'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The review context')),
                ('rating', models.IntegerField(help_text='The rating of this book')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date of the review written')),
                ('date_edited', models.DateTimeField(auto_now_add=True, help_text='Date of the edit', null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
